<a href="https://colab.research.google.com/github/riyaislamshanta482-ctrl/Data-Cleaning-amp-Preprocessing-/blob/main/assingment5_dataset_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Panda and Numpy

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/Garment_Job_Risk_bulk_dataset.xlsx - Sheet1.csv")
df.head(10)
df.tail(10)

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
2490,Rasel Hossain,Pallmall Group,3,Dyeing,52,Medium,NaN,Average,0,Healthy,Basic,Day,Occasional,Medium
2491,Mariam Noor,Pallmall Group,23,Sewing,40,Low,Light,Poor,1,Healthy,Basic,Day,Frequent,Medium
2492,Abdul Latif,Pallmall Group,33,Cutting,48,NaN,Light,Poor,0,Healthy,Basic,Day,Rare,Medium
2493,Fariha Khan,Pallmall Group,29,Packaging,58,Medium,Heavy,Good,0,Healthy,Advanced,Day,Frequent,Medium
2494,Fariha Khan,Pallmall Group,17,Cutting,64,Medium,Light,Poor,1,Healthy,NaN,Evening,Frequent,High
2495,Shamina Begum,Pallmall Group,18,Dyeing,32,NaN,Heavy,Average,0,Healthy,Basic,Day,Occasional,Medium
2496,Fariha Khan,Pallmall Group,30,Dyeing,40,Medium,Light,Average,1,Healthy,Basic,Day,Frequent,Medium
2497,Fariha Khan,Pallmall Group,18,Packaging,55,High,Light,Poor,2,Healthy,NaN,Night,Occasional,High
2498,Mushfiqur Rahman,Pallmall Group,18,Cutting,52,High,Light,Average,0,Minor_Chronic,Basic,Day,Occasional,Low
2499,Mushfiqur Rahman,Pallmall Group,21,Packaging,62,Medium,NaN,Average,1,Minor_Chronic,Basic,Day,Occasional,Low

#

## 1. Missing Values Handling

### Problem Detection

```python
df.isnull().sum()
df.isnull().mean()*100
```

### Interpretation

- Few missing values (<5%) → usually safe to drop.
- Numeric columns → Mean/Median.
- Categorical columns → Mode.
- Time series → Forward Fill / Backward Fill.

### Solutions

- Drop rows
- Drop columns
- Mean Imputation
- Median Imputation
- Mode Imputation
- Forward Fill
- Backward Fill

In [ ]:
 # copy the orginal dataset
df1=df.copy()
df1

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
0,Taslima Akter,Pallmall Group,38,Packaging,41,Medium,Light,Average,2,Healthy,Basic,Day,Occasional,Low
1,Rasel Hossain,Pallmall Group,28,Packaging,51,Low,Light,Average,0,Minor_Chronic,Basic,Day,Frequent,Low
2,Abdul Latif,Pallmall Group,14,Supervisor,68,Low,NaN,Average,0,Healthy,NaN,Night,Frequent,Medium
3,Nazia Sultana,Pallmall Group,7,Sewing,28,High,NaN,Average,0,Healthy,Basic,Day,Occasional,Low
4,Nazia Sultana,Pallmall Group,20,Packaging,49,NaN,Light,Average,0,Healthy,Advanced,Day,Frequent,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,Shamina Begum,Pallmall Group,18,Dyeing,32,NaN,Heavy,Average,0,Healthy,Basic,Day,Occasional,Medium
2496,Fariha Khan,Pallmall Group,30,Dyeing,40,Medium,Light,Average,1,Healthy,Basic,Day,Frequent,Medium
2497,Fariha Khan,Pallmall Group,18,Packaging,55,High,Light,Poor,2,Healthy,NaN,Night,Occasional,High
2498,Mushfiqur Rahman,Pallmall Group,18,Cutting,52,High,Light,Average,0,Minor_Chronic,Basic,Day,Occasional,Low
2499,Mushfiqur Rahman,Pallmall Group,21,Packaging,62,Medium,NaN,Average,1,Minor_Chronic,Basic,Day,Occasional,Low

In [ ]:
#shows the null value
df1.isnull().sum()

Name                          0
Garment_Name                  0
Experience_Years              0
Job_Role                      0
Working_Hours_Per_Week        0
Exposure_To_Chemicals      1224
Machine_Use                 454
Workstation_Ergonomics        0
Injury_History                0
Health_Condition              0
Safety_Training             438
Shift_Type                    0
Task_Rotation_Frequency       0
Job_Risk                      0
dtype: int64

In [ ]:
#Show the mean of null value
df1.isnull().mean()*100

Name                        0.00
Garment_Name                0.00
Experience_Years            0.00
Job_Role                    0.00
Working_Hours_Per_Week      0.00
Exposure_To_Chemicals      48.96
Machine_Use                18.16
Workstation_Ergonomics      0.00
Injury_History              0.00
Health_Condition            0.00
Safety_Training            17.52
Shift_Type                  0.00
Task_Rotation_Frequency     0.00
Job_Risk                    0.00
dtype: float64

In [ ]:
#drop rows
df1.dropna(inplace=True)
df1.isnull().sum()

Name                       0
Garment_Name               0
Experience_Years           0
Job_Role                   0
Working_Hours_Per_Week     0
Exposure_To_Chemicals      0
Machine_Use                0
Workstation_Ergonomics     0
Injury_History             0
Health_Condition           0
Safety_Training            0
Shift_Type                 0
Task_Rotation_Frequency    0
Job_Risk                   0
dtype: int64

In [ ]:
#again copy original datase
df2=df.copy()
df2

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
0,Taslima Akter,Pallmall Group,38,Packaging,41,Medium,Light,Average,2,Healthy,Basic,Day,Occasional,Low
1,Rasel Hossain,Pallmall Group,28,Packaging,51,Low,Light,Average,0,Minor_Chronic,Basic,Day,Frequent,Low
2,Abdul Latif,Pallmall Group,14,Supervisor,68,Low,NaN,Average,0,Healthy,NaN,Night,Frequent,Medium
3,Nazia Sultana,Pallmall Group,7,Sewing,28,High,NaN,Average,0,Healthy,Basic,Day,Occasional,Low
4,Nazia Sultana,Pallmall Group,20,Packaging,49,NaN,Light,Average,0,Healthy,Advanced,Day,Frequent,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,Shamina Begum,Pallmall Group,18,Dyeing,32,NaN,Heavy,Average,0,Healthy,Basic,Day,Occasional,Medium
2496,Fariha Khan,Pallmall Group,30,Dyeing,40,Medium,Light,Average,1,Healthy,Basic,Day,Frequent,Medium
2497,Fariha Khan,Pallmall Group,18,Packaging,55,High,Light,Poor,2,Healthy,NaN,Night,Occasional,High
2498,Mushfiqur Rahman,Pallmall Group,18,Cutting,52,High,Light,Average,0,Minor_Chronic,Basic,Day,Occasional,Low
2499,Mushfiqur Rahman,Pallmall Group,21,Packaging,62,Medium,NaN,Average,1,Minor_Chronic,Basic,Day,Occasional,Low

**# actullay this null value ar categorical thats whay we use mode method to get exact value**

In [ ]:
# Mode
df2["Exposure_To_Chemicals"] = df2["Exposure_To_Chemicals"].fillna(df2["Exposure_To_Chemicals"].mode()[0])
df2["Machine_Use"] = df2["Machine_Use"].fillna(df2["Machine_Use"].mode()[0])
df2["Safety_Training"] =df2["Safety_Training"].fillna(df2["Safety_Training"].mode()[0])
df2.isnull().sum()

Name                       0
Garment_Name               0
Experience_Years           0
Job_Role                   0
Working_Hours_Per_Week     0
Exposure_To_Chemicals      0
Machine_Use                0
Workstation_Ergonomics     0
Injury_History             0
Health_Condition           0
Safety_Training            0
Shift_Type                 0
Task_Rotation_Frequency    0
Job_Risk                   0
dtype: int64

Which thing use for fill the null value

In [ ]:
print("Exposure_To_Chemicals =", df2["Exposure_To_Chemicals"].mode()[0])
print("Machine_Use =", df2["Machine_Use"].mode()[0])
print("Safety_Training =", df2["Safety_Training"].mode()[0])

Exposure_To_Chemicals = Low
Machine_Use = Light
Safety_Training = Basic

# 2. Duplicate Data Removal
df.duplicated().sum()

Interpretation

 1.Duplicate records create bias.
 2.Same customer appearing multiple times can distort analysis.

Solutions
Remove exact duplicates.
Remove duplicate IDs.
Keep latest record only.

In [ ]:
#find the Duplicate value
df2.duplicated().sum() # no duplicate value exist

np.int64(0)

# 3. Wrong Format Fix
Common Issues:

Dates stored as object

Numbers stored as strings

Currency/unit symbols inside values

Solutions

Convert date formats

Convert strings to numeric

Normalize categorical values

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     2500 non-null   object
 1   Garment_Name             2500 non-null   object
 2   Experience_Years         2500 non-null   float64
 3   Job_Role                 2500 non-null   object
 4   Working_Hours_Per_Week   2500 non-null   int64
 5   Exposure_To_Chemicals    1276 non-null   object
 6   Machine_Use              2046 non-null   object
 7   Workstation_Ergonomics   2500 non-null   object
 8   Injury_History           2500 non-null   int64
 9   Health_Condition         2500 non-null   object
 10  Safety_Training          2062 non-null   object
 11  Shift_Type               2500 non-null   object
 12  Task_Rotation_Frequency  2500 non-null   object
 13  Job_Risk                 2500 non-null   object
dtypes: float64(1), int64(2), object(11)
memory usage: 273.6+ KB

Find any problem in datset

In [ ]:
for col in df2.select_dtypes(include="object"):
    print("\n", col)
    print(df2[col].value_counts())

 Name
Name
Shamina Begum       266
Shahidul Islam      263
Fariha Khan         256
Nazia Sultana       256
Mushfiqur Rahman    252
Rasel Hossain       247
Rahim Ahmed         247
Abdul Latif         244
Mariam Noor         235
Taslima Akter       234
Name: count, dtype: int64

 Garment_Name
Garment_Name
Pallmall Group    2500
Name: count, dtype: int64

 Job_Role
Job_Role
Sewing                 738
Packaging              529
Cutting                365
Ironing                312
Dyeing                 237
Machine_Maintenance    207
Supervisor             112
Name: count, dtype: int64

 Exposure_To_Chemicals
Exposure_To_Chemicals
Low       634
Medium    476
High      166
Name: count, dtype: int64

 Machine_Use
Machine_Use
Light    1403
Heavy     643
Name: count, dtype: int64

 Workstation_Ergonomics
Workstation_Ergonomics
Average    1300
Poor        683
Good        517
Name: count, dtype: int64

 Health_Condition
Health_Condition
Healthy            1797
Minor_Chronic       504
Serious_Chronic     199
Name: count, dtype: int64

 Safety_Training
Safety_Training
Basic       1385
Advanced     677
Name: count, dtype: int64

 Shift_Type
Shift_Type
Day        1361
Evening     611
Night       528
Name: count, dtype: int64

 Task_Rotation_Frequency
Task_Rotation_Frequency
Occasional    1149
Rare           861
Frequent       490
Name: count, dtype: int64

 Job_Risk
Job_Risk
Low       1050
Medium     900
High       550
Name: count, dtype: int64

**"The dataset was checked for wrong formats, but no issues were found. All columns were already in the correct data type and format."**

In [ ]:
df2.dtypes

Name                        object
Garment_Name                object
Experience_Years           float64
Job_Role                    object
Working_Hours_Per_Week       int64
Exposure_To_Chemicals       object
Machine_Use                 object
Workstation_Ergonomics      object
Injury_History               int64
Health_Condition            object
Safety_Training             object
Shift_Type                  object
Task_Rotation_Frequency     object
Job_Risk                    object
dtype: object

# 4. Inconsistent Labels
Problem Detection

Sample

df["city"].unique()

df["brand"].unique()

Interpretation

Same entity represented differently.

Example:

Apple
apple
APPLE

Solutions

Case normalization

Spelling correction

Synonym mapping

"Categorical values were checked using unique(). No inconsistent labels were found."

In [ ]:
for col in df2.select_dtypes(include="object"):
    print("\n", col)
    print(df2[col].value_counts())

 Name
Name
Shamina Begum       266
Shahidul Islam      263
Fariha Khan         256
Nazia Sultana       256
Mushfiqur Rahman    252
Rasel Hossain       247
Rahim Ahmed         247
Abdul Latif         244
Mariam Noor         235
Taslima Akter       234
Name: count, dtype: int64

 Garment_Name
Garment_Name
Pallmall Group    2500
Name: count, dtype: int64

 Job_Role
Job_Role
Sewing                 738
Packaging              529
Cutting                365
Ironing                312
Dyeing                 237
Machine_Maintenance    207
Supervisor             112
Name: count, dtype: int64

 Exposure_To_Chemicals
Exposure_To_Chemicals
Low       634
Medium    476
High      166
Name: count, dtype: int64

 Machine_Use
Machine_Use
Light    1403
Heavy     643
Name: count, dtype: int64

 Workstation_Ergonomics
Workstation_Ergonomics
Average    1300
Poor        683
Good        517
Name: count, dtype: int64

 Health_Condition
Health_Condition
Healthy            1797
Minor_Chronic       504
Serious_Chronic     199
Name: count, dtype: int64

 Safety_Training
Safety_Training
Basic       1385
Advanced     677
Name: count, dtype: int64

 Shift_Type
Shift_Type
Day        1361
Evening     611
Night       528
Name: count, dtype: int64

 Task_Rotation_Frequency
Task_Rotation_Frequency
Occasional    1149
Rare           861
Frequent       490
Name: count, dtype: int64

 Job_Risk
Job_Risk
Low       1050
Medium     900
High       550
Name: count, dtype: int64

5. Outlier Detection & Handling
Problem Detection

Methods:

Boxplot

IQR

Z-Score

Domain Rules

Example:

Age < 0 Salary > 10M

Solutions

Remove

Cap (Winsorization)

Log Transform

In [ ]:
#Experience_Years
Q1 = df2["Experience_Years"].quantile(0.25)
Q3 = df2["Experience_Years"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

# Detect
outliers = df2[
    (df2["Experience_Years"] < lower) |
    (df2["Experience_Years"] > upper)
]

# Remove
df2 = df2[
    (df2["Experience_Years"] >= lower) &
    (df2["Experience_Years"] <= upper)
]

# Cap
df2["Experience_Years"] = df2["Experience_Years"].clip(
    lower,
    upper
)

# Log Transform
df2["Experience_Years"] = np.log1p(df2["Experience_Years"])
df2["Experience_Years"]

0       3.663562
1       3.367296
2       2.708050
3       2.079442
4       3.044522
          ...
2495    2.944439
2496    3.433987
2497    2.944439
2498    2.944439
2499    3.091042
Name: Experience_Years, Length: 2500, dtype: float64

6. Noisy Data Filtering

Problem Detection

Examples:

Invalid ages

Typing mistakes

Random sensor noise

Blurry images

Irrelevant text samples

Solutions

Rule-based filtering

Threshold filtering

Quality filtering

In [ ]:
#1. Invalid Values Check (Rule-based Filtering)
# numarical invalid value
df2["Experience_Years"].describe()
df2["Working_Hours_Per_Week"].describe()
df2["Injury_History"].describe()

count    2500.000000
mean        0.579200
std         0.761025
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         6.000000
Name: Injury_History, dtype: float64

In [ ]:
#cheek the noisy data
df2[(df2["Experience_Years"] < 0)]
df2[(df2["Working_Hours_Per_Week"]<0)]
df2[(df2["Injury_History"]<0)]

Empty DataFrame
Columns: [Name, Garment_Name, Experience_Years, Job_Role, Working_Hours_Per_Week, Exposure_To_Chemicals, Machine_Use, Workstation_Ergonomics, Injury_History, Health_Condition, Safety_Training, Shift_Type, Task_Rotation_Frequency, Job_Risk]
Index: []

2. Categorical Values Check

In [ ]:
for col in["Name",
"Garment_Name",
"Job_Role",
"Exposure_To_Chemicals",
"Machine_Use",
"Workstation_Ergonomics",
"Health_Condition",
"Safety_Training",
"Shift_Type",
"Task_Rotation_Frequency",
"Job_Risk"]:
  print(col)
  print(df2[col].unique())

Name
['Taslima Akter' 'Rasel Hossain' 'Abdul Latif' 'Nazia Sultana'
 'Shamina Begum' 'Fariha Khan' 'Rahim Ahmed' 'Shahidul Islam'
 'Mushfiqur Rahman' 'Mariam Noor']
Garment_Name
['Pallmall Group']
Job_Role
['Packaging' 'Supervisor' 'Sewing' 'Ironing' 'Cutting' 'Dyeing'
 'Machine_Maintenance']
Exposure_To_Chemicals
['Medium' 'Low' 'High']
Machine_Use
['Light' 'Heavy']
Workstation_Ergonomics
['Average' 'Good' 'Poor']
Health_Condition
['Healthy' 'Minor_Chronic' 'Serious_Chronic']
Safety_Training
['Basic' 'Advanced']
Shift_Type
['Day' 'Night' 'Evening']
Task_Rotation_Frequency
['Occasional' 'Frequent' 'Rare']
Job_Risk
['Low' 'Medium' 'High']

7. Data Type Consistency Check

Problem Detection

df.dtypes

Common Problems:

int stored as object

boolean stored as string

category stored as object

Solutions

Convert to correct data types.

In [ ]:
# covert float to int
df2["Experience_Years"] = df2["Experience_Years"].astype(int)
df2["Experience_Years"].dtype

dtype('int64')

**Data types were checked and found to be consistent. Numerical columns were in int64 format and categorical columns were in object format.**

In [ ]:
df2.dtypes

Name                       object
Garment_Name               object
Experience_Years            int64
Job_Role                   object
Working_Hours_Per_Week      int64
Exposure_To_Chemicals      object
Machine_Use                object
Workstation_Ergonomics     object
Injury_History              int64
Health_Condition           object
Safety_Training            object
Shift_Type                 object
Task_Rotation_Frequency    object
Job_Risk                   object
dtype: object

8. Schema Validation

Problem Detection

Check:

Missing columns

Extra columns

Wrong column names

Solutions

Validate schema before pipeline execution

In [ ]:
df2.columns

Index(['Name', 'Garment_Name', 'Experience_Years', 'Job_Role',
       'Working_Hours_Per_Week', 'Exposure_To_Chemicals', 'Machine_Use',
       'Workstation_Ergonomics', 'Injury_History', 'Health_Condition',
       'Safety_Training', 'Shift_Type', 'Task_Rotation_Frequency', 'Job_Risk'],
      dtype='object')

The dataset schema was checked and all required columns were present with correct names

In [ ]:
required_cols =['Name',
                'Garment_Name'
                , 'Experience_Years'
                , 'Job_Role',
       'Working_Hours_Per_Week'
       , 'Exposure_To_Chemicals'
       , 'Machine_Use',
       'Workstation_Ergonomics',
                'Injury_History',
                'Health_Condition',
       'Safety_Training',
                'Shift_Type',
                'Task_Rotation_Frequency',
                'Job_Risk'
]
missing = (
    set(required_cols)
    - set(df2.columns)
)

extra = (
    set(df2.columns)
    - set(required_cols)
)

print("Missing:", missing)
print("Extra:", extra)

Missing: set()
Extra: set()

9. Data Range Validation

Problem Detection

Examples:

age > 150

price < 0

probability > 1

Solutions

Apply business/domain rules.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/Garment_Job_Risk_bulk_dataset.xlsx - Sheet1.csv")

In [ ]:
df2=df.copy()
df2

,Name,Garment_Name,Experience_Years,Job_Role,Working_Hours_Per_Week,Exposure_To_Chemicals,Machine_Use,Workstation_Ergonomics,Injury_History,Health_Condition,Safety_Training,Shift_Type,Task_Rotation_Frequency,Job_Risk
0,Taslima Akter,Pallmall Group,38,Packaging,41,Medium,Light,Average,2,Healthy,Basic,Day,Occasional,Low
1,Rasel Hossain,Pallmall Group,28,Packaging,51,Low,Light,Average,0,Minor_Chronic,Basic,Day,Frequent,Low
2,Abdul Latif,Pallmall Group,14,Supervisor,68,Low,NaN,Average,0,Healthy,NaN,Night,Frequent,Medium
3,Nazia Sultana,Pallmall Group,7,Sewing,28,High,NaN,Average,0,Healthy,Basic,Day,Occasional,Low
4,Nazia Sultana,Pallmall Group,20,Packaging,49,NaN,Light,Average,0,Healthy,Advanced,Day,Frequent,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,Shamina Begum,Pallmall Group,18,Dyeing,32,NaN,Heavy,Average,0,Healthy,Basic,Day,Occasional,Medium
2496,Fariha Khan,Pallmall Group,30,Dyeing,40,Medium,Light,Average,1,Healthy,Basic,Day,Frequent,Medium
2497,Fariha Khan,Pallmall Group,18,Packaging,55,High,Light,Poor,2,Healthy,NaN,Night,Occasional,High
2498,Mushfiqur Rahman,Pallmall Group,18,Cutting,52,High,Light,Average,0,Minor_Chronic,Basic,Day,Occasional,Low
2499,Mushfiqur Rahman,Pallmall Group,21,Packaging,62,Medium,NaN,Average,1,Minor_Chronic,Basic,Day,Occasional,Low

In [ ]:

df2["Experience_Years"].describe()

count    2500.000000
mean       20.248800
std        11.832214
min         0.000000
25%        10.000000
50%        21.000000
75%        31.000000
max        40.000000
Name: Experience_Years, dtype: float64

No range violations were found in the Experience_Years column.

In [ ]:
df2[(df2["Experience_Years"] < 0.00) |
    (df2["Experience_Years"] > 40.00)]

Empty DataFrame
Columns: [Name, Garment_Name, Experience_Years, Job_Role, Working_Hours_Per_Week, Exposure_To_Chemicals, Machine_Use, Workstation_Ergonomics, Injury_History, Health_Condition, Safety_Training, Shift_Type, Task_Rotation_Frequency, Job_Risk]
Index: []

In [ ]:
df2["Working_Hours_Per_Week"].describe()

count    2500.000000
mean       48.027600
std        11.702548
min        28.000000
25%        38.000000
50%        48.000000
75%        58.000000
max        68.000000
Name: Working_Hours_Per_Week, dtype: float64

In [ ]:
df2[((df2["Working_Hours_Per_Week"]<28.00)) | ((df2["Working_Hours_Per_Week"]>68.00))]

Empty DataFrame
Columns: [Name, Garment_Name, Experience_Years, Job_Role, Working_Hours_Per_Week, Exposure_To_Chemicals, Machine_Use, Workstation_Ergonomics, Injury_History, Health_Condition, Safety_Training, Shift_Type, Task_Rotation_Frequency, Job_Risk]
Index: []

In [ ]:
df2["Injury_History"].describe()

count    2500.000000
mean        0.579200
std         0.761025
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         6.000000
Name: Injury_History, dtype: float64

In [ ]:
df2[((df2["Injury_History"]<0.0)) |((df2["Injury_History"]>6.0))]

Empty DataFrame
Columns: [Name, Garment_Name, Experience_Years, Job_Role, Working_Hours_Per_Week, Exposure_To_Chemicals, Machine_Use, Workstation_Ergonomics, Injury_History, Health_Condition, Safety_Training, Shift_Type, Task_Rotation_Frequency, Job_Risk]
Index: []

10. Imbalanced Data Check

Problem Detection

df["target"].value_counts()

df["target"].value_counts(normalize=True)*100

Example:


Class 0 → 95% Class 1 → 5%


Interpretation:


Highly Imbalanced Dataset

Solutions

Oversampling

Undersampling

SMOTE

Class Weighting

Better Evaluation Metrics

**The Experience_Years data was well distributed, with no major imbalance.**

In [ ]:
## Check distribution
print(df2["Job_Risk"].value_counts())

Job_Risk
Low       1050
Medium     900
High       550
Name: count, dtype: int64

In [ ]:

#oversampling
# ---------------------
from sklearn.utils import resample

majority = df2[df2.Job_Risk == "Low"]
minority = df2[df2.Job_Risk == "High"]

minority_up = resample(
    minority,
    replace=True,
    n_samples=len(majority),
    random_state=42
)

df2_balanced = pd.concat(
    [majority, minority_up]
)

df2_balanced.Job_Risk.value_counts()

# Undersampling
# ---------------------

majority_down = resample(
    majority,
    replace=False,
    n_samples=len(minority),
    random_state=42
)

df2_under = pd.concat(
    [majority_down, minority]
)

df2_under.Job_Risk.value_counts()

Job_Risk
Low     550
High    550
Name: count, dtype: int64